### ISSUE TITLE
CE NAME 

### ISSUE THREAD

**Issue by SirDeathnote1** [Drawethree/UltraPrisonCore#1]
About the Prison Core and Advanced Enchantment 

Then i drag book and into pickaxes, then the ce Name Trench that gotten remove name however it still work with mining , 
look at the site 

https://gyazo.com/7d7114507f31ff93c04831d2da5b1ca0

Please reslove this

**Comment by Drawethree** [comment]
Hello, currently you can't use another Enchantments plugin along with our enchantment system. That does not make sense. Please decide whether to use our enchanting system or someones else.
