### ISSUE TITLE
Helper spamming console when mining.

### ISSUE THREAD

**Issue by AstonicPI** [Drawethree/UltraPrisonCore#11]
**Describe the bug**
The plugin Helper is flooding my console when mining.

**To Reproduce**
Simply enchant a pickaxe and mine.

**Expected behavior**
Console gets flooded

**Screenshots**
https://paste.helpch.at/ejazesuzif.md

**Comment by Drawethree** [comment]
Thanks for reporting. Fix will be delivered in 1.5.3
