### ISSUE TITLE
Customise Enchant Menu

### ISSUE THREAD

**Issue by RagnarLothbrok-Odin** [Drawethree/UltraPrisonCore#16]
I request that users may further customise the enchant menu, by adding the ability to remove the top 3 default items (disenchant, the pick, and help)

Removing these from the enchants.yml current does not remove them from the GUI, due to the config rewriting it, a simple toggle to disable these items would be a good solution. Ex: `enabled: false`

**Comment by Drawethree** [comment]
Hello @RagnarLothbrok-Odin 
Thank you for your suggestion, I can add that in future update.

**Comment by Drawethree** [comment]
Hello @RagnarLothbrok-Odin 
I have implemented specific changes for Enchant / Disenchat GUI.

Changes in 1.5.9:
In enchants.yml added following:

- Under section enchant_menu, added "pickaxe_enabled" config option
- Under section enchant_menu.help_item, added "enabled" config option
- Under section enchant_menu.disenchant_item, added "enabled" config option
- Under section disenchant_menu, added "pickaxe_enabled" config option
- Under section disenchant_menu.help_item, added "enabled" config option
