### ISSUE TITLE
Token Duplication Glitch

### ISSUE THREAD

**Issue by Luk14** [Drawethree/UltraPrisonCore#19]
**Describe the bug**
You are able to redeem unlimited tokens if the token item is placed in your off-hand

**To Reproduce**
Steps to reproduce the behaviour:
1. /tokens withdraw 10
2. Put the token item in your off-hand
3. Click the off-hand button [Tokens get added but Items does not go away]

**Expected behaviour**
The item should disappear when redeemed

**Extra Info**
Server Version: Purpur 1.16.5 [latest build]
Plugin Version: Most up to date

**Comment by Drawethree** [comment]
Thanks for reporting. Will be delivered in 1.5.11
