### ISSUE TITLE
LuckyBlocks

### ISSUE THREAD

**Issue by Aleehx** [Drawethree/UltraPrisonCore#2]
**Describe the bug**
When you try to use Explosive, or any spell that makes an explosion, near a luckyblock, it doesn't give the rewards, but gives the rewards only when it is destroyed

**Expected behavior**
I would like that when the luckyblock explodes it gives the reward even if it was not destroyed itself, but with an explosive Enchant

**Comment by Drawethree** [comment]
Hello Aleehx, thank you for reporting. Going to investigate and get back to you with my results.

**Comment by Drawethree** [comment]
Hello @Aleehx 
I can see the issue. Fixes for enchants will be deployed in 1.5.2 update.
