### ISSUE TITLE
Ultra Prison Core - Features & Bugs

### ISSUE THREAD

**Issue by ghost** [Drawethree/UltraPrisonCore#26]
**Chat**
Add a option to allow placeholders so we can show prestige in front of our nicknames in chat using essentialsx.

**Pickaxe**
Add the option to allow the pickaxe to be soul-bound so users cannot drop it, moved it to another inventory, cleared or dropped when killed.

Add a option to allow the placeholder pickaxe level to be in the name of the pickaxe.

Add a option to allow us to change the command to bring up the enchantment menu, such as  /etshop or /enchant instead of on click. When clicking with the pickaxe in hand it brings up the enchantment menu, however some of us use npcs to run commands and mcmmo on prison. We cannot use these because it triggers the menu instead.

Add a option to allow the pickaxe to automatically change depending on what block your hitting. 
I don't mean that if you have the pickaxe and another tool in your inventory, that it would switch to it. I am saying that the actual pickaxe changes. For example, when breaking certain blocks it would be a pickaxe, and then automatically change to a axe when hitting any wood block, sword when hitting players or entities, shovel and so on.

**Disenchanting**
Add a option to allow your pickaxe to be fully unenchanted with a confirm gui for the disenchanter. 
This would be a option and the gui would only show if we have this option toggled. If you don't, then you will get the way in comes to where you will be able to take off certain enchants.

**Mines**
Add a command to go to the current mine that you are at, using /mine.

Add a command to see all the available and unavailable mines along with their per drop, using /mines.

Add a option that mine resets are on a timer or by the percent of blocks that are mined.

**Boosters**
Add the option for a global booster to where you can boost 2x and 3x for a time limit with the options of sell and etokens with optional xp.  This would be a physical item that is credited to the players inventory. In doing this, add /booster that brings up a gui to see all active boosters for the server. Make it so only one booster of each type can be active at one time per server. Boosters do not stack in time. Make it so you must wait to activate a booster until the current one expires. 

**Backpacks:**
Add the option for backpacks can be bought using e-tokens in either a shop gui or at least by a command so we can make our own shops.

Add the option for backpacks of our choosing to be merged into higher tiers, giving us more slots by using /bpmerge.

Add the option to only allow blocks that are mined go into the backpack, and make it so they automatically go there.

Add the option that if you place a backpack to the ground that all blocks inside of it go into your inventory. The backpack is not able to be placed on the ground.

Add the option to allow to choose what material the backpack is in inventory.

**Enchants:**
Efficiency - Allows pick to break blocks faster.
Fortune - Increases drops per blocks broken.
Jackhammer - Chance to clear one whole layer of the mine.
Explosive - Spawn TnT explosions as you mine.
Regrowth - Recover health and hunger while using your pickaxe.
Speed - Allows you to run faster while using your pickaxe.
Haste - Allows you to swing your pickaxe faster.
Auto Mine - Like explosive except automatic.
Merchant - Chance to sell a block for 2x it's value.
Enrage - Chance to throw you into a rage spawning an RPG everytime you swing your pickaxe for 3s.
Auto Sell - Every 6 seconds, you will sell 3x block, upgradeable based on yoru level.
Laser - Chance to shoot a laser that mines out in all directions and doesn't stop until it hits the mine's edge or air.

**Comment by donvdp** [comment]
Great list. i'd like to add to enchants:
Silktouch - Allows you to silktouch blocks like vanilla minecraft.

**Comment by ThinkRusty87** [comment]
Updated

**Comment by ThinkRusty87** [comment]
Updated

**Comment by Drawethree** [comment]
Hello, please do not post feature requests in there, instead post them on our Discord. Also lot of there things are already in the core.
