### ISSUE TITLE
Rank multiplier not working

### ISSUE THREAD

**Issue by donvdp** [Drawethree/UltraPrisonCore#27]
I cannot get the ranked multiplier to work, and also i do not understand how to change from ranked token multiplier to ranked sell multiplier. here below

I shut down my server and edited the multiplier.yml file to contain:

![image](https://user-images.githubusercontent.com/10013800/132959637-4e8212a4-1f89-4b07-853c-f55d5ccb840e.png)

Then i booted my server up again.

Using luckperms i added the permission node "ultraprison.multiplier.p1" to the group "prisonp1". (at stated in the wiki)

I added the ingame user "donvdp" to the group "prisonp1"

Using ingame command "/multi" i see **no** active multipliers:

![image](https://user-images.githubusercontent.com/10013800/132959757-c2e04b73-e95a-49c3-92cf-8cb69b85cae2.png)

Chatting about this problem on discord i also tried to change the rank sequence as listed in below image:
![image](https://user-images.githubusercontent.com/10013800/132959774-1cf11739-aaa3-4026-9b0d-cd60cca10aff.png)

This also did not fix the problem. I do not know how to get this to work so i think it is an bug.

I also tried to set the permission node "ultraprison.multiplier.p1" directly to the player "donvdp". This also did not fix this issue. 

I am running papermc 1.16.5 build # 783

**Comment by Drawethree** [comment]
Hello, if you have set option use-luckperms-groups: true in multipliers.yml, the permission node is group.<group>. Otherwise it is ultraprison.multiplier.<group>.
