### ISSUE TITLE
Ranks.yml - CMD

### ISSUE THREAD

**Issue by x0xDevilx0x** [Drawethree/UltraPrisonCore#40]
Sorry if this was the wrong place to ask this, but the discord link you provided wasn't working so I didn't knew how to contact.

In the `Ranks.yml` file under the **CMD** config, how do u make the command run by the PLAYER insted of the console ? 

Thank You.

**Comment by Drawethree** [comment]
Hello, CMDs under ranks are intended to be ran from console.
